server:
  port: 5555

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8182"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8180/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/site-core
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8183/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-form
            - JwtAuthFilter

jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
