server:
  port: 8180
  servlet:
    context-path: /site-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB


upload:
  path: C:/Users/Ilya/Desktop/MyProject/materials
